---
- name: ensure Java is installed
  apt:
    name: "openjdk-8-jdk"
    state: present
    update_cache: yes
  become: yes

- name: download deb package
  get_url:
    dest: "/etc/{{ elasticsearch_deb_file }}"
    url: "https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_deb_file }}"
    checksum: "sha512:https://artifacts.elastic.co/downloads/elasticsearch/{{ elasticsearch_deb_file }}.sha512"
  become: yes

- name: install from deb package
  apt:
    deb: "/etc/{{ elasticsearch_deb_file }}"
  become: yes

- name: update config files
  template:
    dest: /etc/elasticsearch/elasticsearch.yml
    src: elasticsearch.yml.j2
  become: yes
  notify: restart elasticsearch
